# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-26 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharApp',
            fields=[
                ('app_id', models.AutoField(primary_key=True, serialize=False)),
                ('char_name', models.CharField(max_length=80, verbose_name=b'Character Name')),
                ('date_applied', models.DateTimeField(verbose_name=b'Date Applied')),
                ('background', models.TextField(verbose_name=b'Background')),
                ('player_id', models.IntegerField(default=1, verbose_name=b'Player ID')),
                ('submitted', models.BooleanField(default=False)),
            ],
        ),
    ]
